name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/checkout@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: install
      run: pip install --upgrade pip &&|
              pip install -r requirements.txt

    - name: install-gcp
      run: pip install --upgrade pip &&|
              pip install -r requirements-gcp.txt

    - name: install-aws
      run: pip install --upgrade pip &&\
          		pip install -r requirements-aws.txt

    - name: install-amazon-linux
      run: pip install --upgrade pip &&\
		          pip install -r amazon-linux.txt

    - name: lint
      run: pylint --disable=R,C hello.py

    - name: format
      run: black *.py

    - name: test
      run: python -m pytest -vv --cov=hello test_hello.py


