name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    - name: Lint code
      run: |
        pylint --disable=R,C .github/workflows/hello.py

    - name: Format code
      run: |
        pip install black
        black .github/workflows/*.py

    - name: Test
      run: |
        python -m pytest -vv --cov=hello .github/workflows/test_hello.py
